In [1]:
from sqlalchemy import create_engine, text, select, Table, Column, Integer, String, MetaData
import pandas as pd

# Create Conection

In [3]:
#conex√£o com bd
engine = create_engine("mssql+pyodbc://fdebierne:ggyQHJODSFH%%!GJJKS@metrix-wh.database.windows.net:1433/XXXFREMF_BACKUP?driver=ODBC+Driver+17+for+SQL+Server", echo = True)
conection = engine.connect()

2023-08-28 08:36:36,057 INFO sqlalchemy.engine.Engine SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
2023-08-28 08:36:36,059 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-08-28 08:36:36,203 INFO sqlalchemy.engine.Engine SELECT schema_name()
2023-08-28 08:36:36,206 INFO sqlalchemy.engine.Engine [generated in 0.00275s] ()
2023-08-28 08:36:36,496 INFO sqlalchemy.engine.Engine SELECT CAST('test max support' AS NVARCHAR(max))
2023-08-28 08:36:36,496 INFO sqlalchemy.engine.Engine [generated in 0.00064s] ()

## Example how to get a table

In [181]:
sql = """ SELECT *
    FROM MACRO_MEAN_SDV M
    WHERE M.STATEMENTYEAR = '2021'
    """
MACRO_MEAN_SDV_LPLIST_AVM_LPLIST_AVM_LPLIST_AVM_LPLIST_AVM_LPLIST_AVM_DF = pd.read_sql( sql, con=conection)

2023-08-23 16:18:51,192 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
FROM [INFORMATION_SCHEMA].[TABLES]
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
2023-08-23 16:18:51,192 INFO sqlalchemy.engine.Engine [generated in 0.00121s] ('BASE TABLE', " SELECT *\n    FROM MACRO_MEAN_SDV M\n    WHERE M.STATEMENTYEAR = '2021'\n    ", 'dbo')
2023-08-23 16:18:51,489 INFO sqlalchemy.engine.Engine  SELECT *
    FROM MACRO_MEAN_SDV M
    WHERE M.STATEMENTYEAR = '2021'

2023-08-23 16:18:51,489 INFO sqlalchemy.engine.Engine [raw sql] ()

In [182]:
MACRO_MEAN_SDV_DF

,MDRA_SUBTYPE_YR,NARRATIVE,MDRA_SUBTYPE,MDRA,SUBTYPE,STATEMENTYEAR,NumProperties_DATA,NumProperties_REV,NumProperties_FF,NumProperties_VAL,...,REV_2YR_PCT_CH_FWD_SDV,EXP_2YR_PCT_CH_FWD_SDV,NOI_2YR_PCT_CH_FWD_SDV,NCF_2YR_PCT_CH_FWD_SDV,CAPEX_2YR_PCT_CH_FWD_SDV,REV_3YR_PCT_CH_FWD_SDV,EXP_3YR_PCT_CH_FWD_SDV,NOI_3YR_PCT_CH_FWD_SDV,NCF_3YR_PCT_CH_FWD_SDV,CAPEX_3YR_PCT_CH_FWD_SDV
0,TN-Nashville-Davidson-Murfreesboro-Franklin_AL...,NaN,TN-Nashville-Davidson-Murfreesboro-Franklin_ALL,TN-Nashville-Davidson-Murfreesboro-Franklin,ALL,2021,174,169,134,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,NaN,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,TN-Nashville-Davidson-Murfreesboro-Franklin,GARDEN(ALL),2021,151,146,115,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,NaN,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,TN-Nashville-Davidson-Murfreesboro-Franklin,GARDEN(SB),2021,29,29,25,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,NaN,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,TN-Nashville-Davidson-Murfreesboro-Franklin,GARDEN,2021,122,117,90,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,NaN,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,TN-Nashville-Davidson-Murfreesboro-Franklin,GARDEN_MIDRISE(SB),2021,29,29,25,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,TN-AR-MS-Memphis_GARDEN_MIDRISE_HIRISE_2021,NaN,TN-AR-MS-Memphis_GARDEN_MIDRISE_HIRISE,TN-AR-MS-Memphis,GARDEN_MIDRISE_HIRISE,2021,51,50,39,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
831,TN-GA-Chattanooga_ALL_2021,NaN,TN-GA-Chattanooga_ALL,TN-GA-Chattanooga,ALL,2021,39,36,29,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
832,TN-GA-Chattanooga_GARDEN(ALL)_2021,NaN,TN-GA-Chattanooga_GARDEN(ALL),TN-GA-Chattanooga,GARDEN(ALL),2021,32,29,24,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
833,TN-Knoxville_ALL_2021,NaN,TN-Knoxville_ALL,TN-Knoxville,ALL,2021,53,50,38,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
834,TN-Knoxville_GARDEN(ALL)_2021,NaN,TN-Knoxville_GARDEN(ALL),TN-Knoxville,GARDEN(ALL),2021,43,40,29,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Imputs Procedure

In [236]:
# Filter
MDRA = 'Southeast' # Define the region of interest base on NCREIF
UWDATE_START = pd.Timestamp('2021-07-29')
UWDATE_END  = pd.Timestamp('2021-10-29')
SUBTYPE = 'ALL'
STATEMENTYEAR2 = 2021
MIN_NUMPROPS_FOR_US_MEAN_CALC = 1
DEPVAR='UW_CAPRATE'
MIN_NUMPROPS_IN_ST_MDRA_YR_TO_FIT_MODEL = 20
MODELNUM=0

# CHECK IF THERE ARE 1) ENOUGH OBSERVATIONS AND 2) US MEAN IS CALCULATED

## Imput Tables

### Get MACRO_MEAN_SDV Date

In [5]:
sql = """ SELECT *
    FROM MACRO_MEAN_SDV M
    WHERE M.STATEMENTYEAR = '2021'
    """
MACRO_MEAN_SDV_DF= pd.read_sql( sql, con=engine.connect())
MACRO_MEAN_SDV_DF.to_excel("source/MACRO_MEAN_SDV_DF.xlsx", index=False)
MACRO_MEAN_SDV_DF = pd.read_excel('source/MACRO_MEAN_SDV_DF.xlsx')

#Table MACRO_MEAN_SDV_DF

2023-08-28 08:36:59,525 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
FROM [INFORMATION_SCHEMA].[TABLES]
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
2023-08-28 08:36:59,526 INFO sqlalchemy.engine.Engine [generated in 0.00166s] ('BASE TABLE', " SELECT *\n    FROM MACRO_MEAN_SDV M\n    WHERE M.STATEMENTYEAR = '2021'\n    ", 'dbo')
2023-08-28 08:36:59,814 INFO sqlalchemy.engine.Engine  SELECT *
    FROM MACRO_MEAN_SDV M
    WHERE M.STATEMENTYEAR = '2021'

2023-08-28 08:36:59,814 INFO sqlalchemy.engine.Engine [raw sql] ()

### Get LPLIST_AVM

In [276]:
sql = """ SELECT *
    FROM LPLIST_AVM
    WHERE CENSUSYEAR = '2021'
    """
LPLIST_AVM_DF = pd.read_sql( sql, con=engine.connect())
LPLIST_AVM_DF.to_excel("source/LPLIST_AVM_DF.xlsx", index=False)
LPLIST_AVM_DF = pd.read_excel('source/LPLIST_AVM_DF.xlsx')

#table LPLIST_AVM_DF

2023-08-28 21:31:32,132 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
FROM [INFORMATION_SCHEMA].[TABLES]
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
2023-08-28 21:31:32,148 INFO sqlalchemy.engine.Engine [cached since 4.648e+04s ago] ('BASE TABLE', " SELECT *\n    FROM LPLIST_AVM\n    WHERE CENSUSYEAR = '2021'\n    ", 'dbo')
2023-08-28 21:31:33,925 INFO sqlalchemy.engine.Engine  SELECT *
    FROM LPLIST_AVM
    WHERE CENSUSYEAR = '2021'

2023-08-28 21:31:33,926 INFO sqlalchemy.engine.Engine [raw sql] ()

In [281]:
df = LPLIST_AVM_DF['UW_CAPRATE'].sort_values(ascending=True)
df

27      0.014666
761     0.015505
5142    0.022983
3706    0.023492
6827    0.024721
          ...
7998         NaN
7999         NaN
8000         NaN
8001         NaN
8002         NaN
Name: UW_CAPRATE, Length: 8008, dtype: float64

## ALL US NUMBERS

In [7]:
#NumProperties_UW is used to verify something
NumProperties_UW_Filter = MACRO_MEAN_SDV_DF[(MACRO_MEAN_SDV_DF["SUBTYPE"] == 'ALL') & (MACRO_MEAN_SDV_DF["MDRA"] == 'ALLUS') & (MACRO_MEAN_SDV_DF["STATEMENTYEAR"] == STATEMENTYEAR2)] 

NumProperties_UW = NumProperties_UW_Filter["NumProperties_UW"].max()
NumProperties_UW

3969

## SUBTYPE_MDRA SDV

In [10]:
filtered_data = LPLIST_AVM_DF[
    (LPLIST_AVM_DF['UWDATE'] >= UWDATE_START) & (LPLIST_AVM_DF['UWDATE'] <= UWDATE_END) &
    (
        (LPLIST_AVM_DF['NCREIFMetro'] == MDRA) |
        (LPLIST_AVM_DF['NCREIFDivision'] == MDRA) |
        (LPLIST_AVM_DF['NCREIFRegion'] == MDRA) |
        (MDRA == 'ALLUS')
    ) &
    (
        (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == SUBTYPE) |
        (SUBTYPE == 'ALL') |
        (
            ((LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN') | (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE')) &
            (SUBTYPE == 'GARDEN_MIDRISE')
        ) |
        (
            ((LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE') | (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'HIRISE')) &
            (SUBTYPE == 'MIDRISE_HIRISE')
        ) |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'HIRISE')
            ) & (SUBTYPE == 'GARDEN_MIDRISE_HIRISE')
        ) |
        (
            ((LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN(SB)') | (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN')) &
            (SUBTYPE == 'GARDEN(ALL)')
        ) |
        (
            ((LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE(SB)') | (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE')) &
            (SUBTYPE == 'MIDRISE(ALL)')
        ) |
        (
            ((LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN(SB)') | (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE(SB)')) &
            (SUBTYPE == 'GARDEN_MIDRISE(SB)')
        )
    ) & (LPLIST_AVM_DF['DATANUM'].isin([0, 1, 2, 3]))
    ]

if DEPVAR == 'UW_CAPRATE':
    filtered_data = filtered_data[filtered_data['UW_CAPRATE'].notnull()]
elif DEPVAR == 'UW_REV_ACTUAL_RATIO':
    filtered_data = filtered_data[filtered_data['UW_REV_ACTUAL_RATIO'].notnull()]
elif DEPVAR == 'UW_EXP_ACTUAL_RATIO':
    filtered_data = filtered_data[filtered_data['UW_EXP_ACTUAL_RATIO'].notnull()]


#Temos uma diferen√ßa de 1 linha, provavelmente por causa de case insensitive

## PERFORM THE CALC

In [9]:
if NumProperties_UW > MIN_NUMPROPS_FOR_US_MEAN_CALC and len(filtered_data) >= MIN_NUMPROPS_IN_ST_MDRA_YR_TO_FIT_MODEL:
    STATEMENTYEAR1 = STATEMENTYEAR2
    def define_variables(variable_name):
        #primeiro pegamos o nome da variavel e separamos por split
        variables_name_split = variable_name.split('_')

        for v in variables_name_split:
            if(v == 'MDRA'):
                variable = MDRA
            elif(v == 'SUBTYPE'):
                variable = variable + '_' + str(SUBTYPE)
            elif(v == 'YR1'):
                variable = variable + '_' + str(STATEMENTYEAR1)
            elif(v == 'YR2'):
                variable = variable + '_' + str(STATEMENTYEAR2)
            elif(v == 'VAR'):
                variable = variable + '_' + str(DEPVAR)
            elif(v == 'NUM'):
                variable = variable + '_' + str(MODELNUM)
        
        return variable 
        
    variables = {"MDRA_SUBTYPE_YR1_YR2_VAR_NUM": define_variables('MDRA_SUBTYPE_YR1_YR2_VAR_NUM'), "MDRA_SUBTYPE_YR1_YR2": define_variables('MDRA_SUBTYPE_YR1_YR2'), "MDRA_SUBTYPE_YR2_VAR": define_variables('MDRA_SUBTYPE_YR2_VAR'), "MDRA_SUBTYPE_VAR": define_variables('MDRA_SUBTYPE_VAR'), "MDRA_SUBTYPE_YR2":define_variables('MDRA_SUBTYPE_YR2')}

## SUBTYPE_MDRA SDV

### TEMP TUS

In [115]:
conditions_TUS = (
    (MACRO_MEAN_SDV_DF['SUBTYPE'] == 'ALL') &
    (MACRO_MEAN_SDV_DF['MDRA'] == 'ALLUS') &
    (MACRO_MEAN_SDV_DF['STATEMENTYEAR'] >= STATEMENTYEAR1) &
    (MACRO_MEAN_SDV_DF['STATEMENTYEAR'] <= STATEMENTYEAR2) &
    (MACRO_MEAN_SDV_DF['NumProperties_UW'] > MIN_NUMPROPS_FOR_US_MEAN_CALC)
)

In [136]:
#NUMPROPYEAR column calculation
NUMPROPYEAR_DF = LPLIST_AVM_DF[
    (LPLIST_AVM_DF['UWDATE'] >= UWDATE_START) &
    (LPLIST_AVM_DF['UWDATE'] <= UWDATE_END) &
    (
        (LPLIST_AVM_DF['NCREIFMetro'] == MDRA) |
        (LPLIST_AVM_DF['NCREIFDivision'] == MDRA) |
        (LPLIST_AVM_DF['NCREIFRegion'] == MDRA) |
        (MDRA == 'ALLUS')
    
    ) &
    (
        (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == SUBTYPE) |
        (SUBTYPE == 'ALL') |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE')
            ) 
            & (SUBTYPE == 'GARDEN_MIDRISE')
        ) |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'HIRISE')
            )
            & (SUBTYPE == 'MIDRISE_HIRISE')
        ) |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'HIRISE')
            )  
            & (SUBTYPE == 'GARDEN_MIDRISE_HIRISE')
        ) |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN(SB)') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN')
            ) & (SUBTYPE == 'GARDEN(ALL)')
        ) |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE(SB)') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE')
            ) & (SUBTYPE == 'MIDRISE(ALL)')
        ) |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN(SB)') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE(SB)')
            ) & (SUBTYPE == 'GARDEN_MIDRISE(SB)')
        )
    ) &
    (LPLIST_AVM_DF['DATANUM'].isin([0, 1, 2, 3])) &
    (
        (
            (DEPVAR == 'UW_CAPRATE') & (LPLIST_AVM_DF[DEPVAR].notnull())
        ) |
        (
            (DEPVAR == 'UW_REV_ACTUAL_RATIO') & (LPLIST_AVM_DF[DEPVAR].notnull())
        ) |
        (
            (DEPVAR == 'UW_EXP_ACTUAL_RATIO') & (LPLIST_AVM_DF[DEPVAR].notnull())
        )
    ) 
    ]
NUMPROPYEAR = len(NUMPROPYEAR_DF)
NUMPROPYEAR

164

In [137]:
#v column calculation
V_TUS_DF = MACRO_MEAN_SDV_DF[
        (
            (
                (DEPVAR == 'UW_CAPRATE') & (MACRO_MEAN_SDV_DF[DEPVAR].notnull())
            ) |
            (
                (DEPVAR == 'UW_REV_ACTUAL_RATIO') & (MACRO_MEAN_SDV_DF[DEPVAR].notnull())
            ) |
            (
                (DEPVAR == 'UW_EXP_ACTUAL_RATIO') & (MACRO_MEAN_SDV_DF[DEPVAR].notnull())
            )
        ) 
    ]

V_TUS = V_TUS_DF[DEPVAR]
V_TUS

0      0.045706
1      0.045351
2      0.044415
3      0.045551
4      0.044415
         ...
830    0.055203
831    0.053530
832    0.053530
833    0.051157
834    0.051157
Name: UW_CAPRATE, Length: 820, dtype: float64

In [219]:
tus = {
    'STATEMENTYEAR': MACRO_MEAN_SDV_DF['STATEMENTYEAR'],
    'NUMPROPYEAR': NUMPROPYEAR,
    'V': V_TUS,
    'YearBuiltRenov': MACRO_MEAN_SDV_DF['YearBuiltRenov'],
    'PopulationPerSqMile': MACRO_MEAN_SDV_DF['PopulationPerSqMile'],
    'MedianHHInc': MACRO_MEAN_SDV_DF['MedianHHInc'],
    'MedianHomeVal': MACRO_MEAN_SDV_DF['MedianHomeVal'],
    'Median_Rent': MACRO_MEAN_SDV_DF['Median_Rent'],
    'MedianAge': MACRO_MEAN_SDV_DF['MedianAge'],
    'Median_Owner_Costs': MACRO_MEAN_SDV_DF['Median_Owner_Costs'],
    'RenterPCT': MACRO_MEAN_SDV_DF['RenterPCT'],
    'CashRentOver30PCT': MACRO_MEAN_SDV_DF['CashRentOver30PCT'],
    'BachelorsOrMorePCT': MACRO_MEAN_SDV_DF['BachelorsOrMorePCT'],
    'UnemploymentPCT': MACRO_MEAN_SDV_DF['UnemploymentPCT'],
    'MngtFinancePCT': MACRO_MEAN_SDV_DF['MngtFinancePCT'],
    'MovedIn2010orLaterPCT': MACRO_MEAN_SDV_DF['MovedIn2010orLaterPCT'],
    'HPI_1YRCH': MACRO_MEAN_SDV_DF['HPI_1YRCH'],
    'NumUnits': MACRO_MEAN_SDV_DF['NumUnits'],
    'HPI_METRO_1YRCH': MACRO_MEAN_SDV_DF['HPI_METRO_1YRCH']
}

TUS_DF_ORIGIN = pd.DataFrame(tus)

columns_to_select = ['STATEMENTYEAR', 'NUMPROPYEAR', 'V', 'YearBuiltRenov', 'PopulationPerSqMile',
                     'MedianHHInc', 'MedianHomeVal', 'Median_Rent', 'MedianAge', 'Median_Owner_Costs',
                     'RenterPCT', 'CashRentOver30PCT', 'BachelorsOrMorePCT', 'UnemploymentPCT', 'MngtFinancePCT',
                     'MovedIn2010orLaterPCT', 'HPI_1YRCH', 'NumUnits', 'HPI_METRO_1YRCH']

TUS_DF = TUS_DF_ORIGIN.loc[conditions_TUS, columns_to_select].drop_duplicates()
TUS_DF

,STATEMENTYEAR,NUMPROPYEAR,V,YearBuiltRenov,PopulationPerSqMile,MedianHHInc,MedianHomeVal,Median_Rent,MedianAge,Median_Owner_Costs,RenterPCT,CashRentOver30PCT,BachelorsOrMorePCT,UnemploymentPCT,MngtFinancePCT,MovedIn2010orLaterPCT,HPI_1YRCH,NumUnits,HPI_METRO_1YRCH
187,2021,164,0.049551,1996.913141,12754.700769,66494.438173,333975.634543,1318.042929,36.056466,1828.746892,0.575934,0.480738,0.362177,0.061642,0.228082,0.669441,0.113517,143.265957,0.113522

### TEMP T0

In [282]:
#necess√°rio fazer um broadcasted_row para que a quantidade de linhas da temp tus seja igual a quantidadede de linhas da LPLIST_AVM_DF
broadcasted_row = pd.DataFrame([TUS_DF.iloc[0]] * len(LPLIST_AVM_DF), columns=TUS_DF.columns)

#tamb√©m necess√°rio d√° um reset nos index para evitar qualquer erro:
broadcasted_row = broadcasted_row.reset_index(drop = True)
LPLIST_AVM_DF_reset = LPLIST_AVM_DF.reset_index(drop = True)

In [283]:
conditions = (
    (LPLIST_AVM_DF['UWDATE'] >= UWDATE_START) &
    (LPLIST_AVM_DF['UWDATE'] <= UWDATE_END) &
    (broadcasted_row['STATEMENTYEAR'] == STATEMENTYEAR2) &
    (
        (LPLIST_AVM_DF['NCREIFMetro'] == MDRA) |
        (LPLIST_AVM_DF['NCREIFDivision'] == MDRA) |
        (LPLIST_AVM_DF['NCREIFRegion'] == MDRA) |
        (MDRA == 'ALLUS')
    ) &
    (
        (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == SUBTYPE) |
        (SUBTYPE == 'ALL') |
        (
            LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'].isin(['GARDEN', 'MIDRISE']) &
            (SUBTYPE == 'GARDEN_MIDRISE')
        )
    ) &
    (LPLIST_AVM_DF['YearBuiltRenov'].notnull()) &
    (LPLIST_AVM_DF['PopulationPerSqMile'].notnull()) &
    (LPLIST_AVM_DF['MedianHHInc'].notnull()) &
    (LPLIST_AVM_DF['MedianHomeVal'].notnull()) &
    (LPLIST_AVM_DF['Median_Rent'].notnull()) &
    (LPLIST_AVM_DF['MedianAge'].notnull()) &
    (LPLIST_AVM_DF['Median_Owner_Costs'].notnull()) &
    (LPLIST_AVM_DF['RenterPCT'].notnull()) &
    (LPLIST_AVM_DF['CashRentOver30PCT'].notnull()) &
    (LPLIST_AVM_DF['BachelorsOrMorePCT'].notnull()) &
    (LPLIST_AVM_DF['UnemploymentPCT'].notnull()) &
    (LPLIST_AVM_DF['MngtFinancePCT'].notnull()) &
    (LPLIST_AVM_DF['MovedIn2010orLaterPCT'].notnull()) &
    (LPLIST_AVM_DF['HPI_1YRCH'].notnull()) &
    (LPLIST_AVM_DF['NumUnits'].notnull()) &
    (
        (DEPVAR == 'UW_CAPRATE' and LPLIST_AVM_DF['UW_CAPRATE'].notnull()) |
        (DEPVAR == 'UW_REV_ACTUAL_RATIO' and LPLIST_AVM_DF['UW_REV_ACTUAL_RATIO'].notnull()) |
        (DEPVAR == 'UW_EXP_ACTUAL_RATIO' and LPLIST_AVM_DF['UW_EXP_ACTUAL_RATIO'].notnull())
    )
)

In [284]:
#v column calculation
V_T0_DF = LPLIST_AVM_DF[
        (
            (
                (DEPVAR == 'UW_CAPRATE') & (LPLIST_AVM_DF[DEPVAR].notnull())
            ) |
            (
                (DEPVAR == 'UW_REV_ACTUAL_RATIO') & (LPLIST_AVM_DF[DEPVAR].notnull())
            ) |
            (
                (DEPVAR == 'UW_EXP_ACTUAL_RATIO') & (LPLIST_AVM_DF[DEPVAR].notnull())
            )
        ) 
    ]

V_T0 = V_T0_DF[DEPVAR]
V_T0

0       0.055768
1       0.064044
2       0.073334
3       0.074945
4       0.058246
          ...
8003    0.038864
8004    0.034401
8005    0.038595
8006    0.042566
8007    0.045998
Name: UW_CAPRATE, Length: 7325, dtype: float64

In [285]:
#create temp table tus
T0 = {
    'STATEMENTYEAR': broadcasted_row['STATEMENTYEAR'],
    'V': V_T0 - broadcasted_row['V'],
    'V1': LPLIST_AVM_DF['YearBuiltRenov'] - broadcasted_row['YearBuiltRenov'],
    'V2': LPLIST_AVM_DF['PopulationPerSqMile'] - broadcasted_row['PopulationPerSqMile'],
    'V3': LPLIST_AVM_DF['MedianHHInc'] - broadcasted_row['MedianHHInc'],
    'V4': LPLIST_AVM_DF['MedianHomeVal'] - broadcasted_row['MedianHomeVal'],
    'V5': LPLIST_AVM_DF['Median_Rent'] - broadcasted_row['Median_Rent'],
    'V6': LPLIST_AVM_DF['MedianAge'] - broadcasted_row['MedianAge'],
    'V7': LPLIST_AVM_DF['Median_Owner_Costs'] - broadcasted_row['Median_Owner_Costs'],
    'V8': LPLIST_AVM_DF['RenterPCT'] - broadcasted_row['RenterPCT'],
    'V9': LPLIST_AVM_DF['CashRentOver30PCT'] - broadcasted_row['CashRentOver30PCT'],
    'V10': LPLIST_AVM_DF['BachelorsOrMorePCT'] - broadcasted_row['BachelorsOrMorePCT'],
    'V11': LPLIST_AVM_DF['UnemploymentPCT'] - broadcasted_row['UnemploymentPCT'],
    'V13': LPLIST_AVM_DF['MngtFinancePCT'] - broadcasted_row['MngtFinancePCT'],
    'V15': LPLIST_AVM_DF['MovedIn2010orLaterPCT'] - broadcasted_row['MovedIn2010orLaterPCT'],
    'V16': LPLIST_AVM_DF['HPI_1YRCH'] - broadcasted_row['HPI_1YRCH'],
    'V35': LPLIST_AVM_DF['NumUnits'] - broadcasted_row['NumUnits'],
    'V39': LPLIST_AVM_DF['HPI_METRO_1YRCH'] - broadcasted_row['HPI_METRO_1YRCH']
}

T0_DF_ORIGIN = pd.DataFrame(T0)

columns_to_select = ['STATEMENTYEAR','V','V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V13','V15','V16','V35','V39']

T0_DF = T0_DF_ORIGIN.loc[conditions, columns_to_select].drop_duplicates().sort_values(by='V', ascending=True)
##T_DF
T0_DF

,STATEMENTYEAR,V,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V13,V15,V16,V35,V39
6406,2021.0,-0.014690,-9.913141,-10095.241309,-6077.438173,-125475.634543,299.957071,2.843534,-626.746892,-0.290934,0.180262,-0.202177,0.001358,-0.120082,-0.102441,0.081883,-2.265957,0.051950
4464,2021.0,-0.013991,-15.913141,-10121.046923,-1347.438173,-124075.634543,42.957071,-8.756466,-30.746892,-0.216934,0.238262,0.082823,-0.019642,-0.054082,-0.070441,-0.038717,40.734043,0.022162
2343,2021.0,-0.013894,12.086859,-11619.608421,-15177.438173,-197275.634543,-440.042929,8.343534,-747.746892,-0.231934,-0.044738,-0.195177,-0.035642,-0.103082,-0.100441,0.015883,96.734043,0.026415
7227,2021.0,-0.011937,17.086859,-1321.367436,4655.561827,100924.365457,778.957071,30.443534,746.253108,-0.328934,0.248262,0.120823,-0.039642,0.146918,-0.112441,0.036083,-125.265957,0.023174
2924,2021.0,-0.011220,23.086859,-8323.249156,29150.561827,-50575.634543,392.957071,-4.456466,-178.746892,-0.352934,-0.297738,0.154823,-0.039642,0.048918,-0.021441,0.002683,22.734043,0.040656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,2021.0,0.010013,1.086859,-9512.671783,268.561827,-475.634543,471.957071,5.743534,95.253108,0.056066,0.183262,0.107823,-0.044642,-0.005082,0.082559,0.060183,-3.265957,0.082711
5925,2021.0,0.011342,-28.913141,-9703.167027,10208.561827,-71975.634543,-178.042929,9.543534,-208.746892,-0.300934,-0.162738,0.122823,-0.032642,0.097918,-0.090441,0.028483,-100.265957,0.022162
7180,2021.0,0.012785,-12.913141,-11119.795109,-29936.438173,-271175.634543,-472.042929,7.143534,-526.746892,-0.133934,0.160262,-0.169177,-0.017642,0.010918,-0.177441,0.084983,-119.265957,0.033149
6095,2021.0,0.016966,-19.913141,-12416.911824,-15029.438173,-256375.634543,-383.042929,1.143534,-862.746892,-0.311934,-0.129738,-0.139177,0.010358,-0.111082,-0.241441,0.217783,-103.265957,0.082711
7027,2021.0,0.020620,22.086859,-10135.522687,-28109.438173,-270875.634543,-405.042929,-7.156466,-796.746892,0.125066,0.004262,-0.291177,0.022358,-0.052082,0.089559,0.106683,-131.265957,0.022162