In [92]:
from sqlalchemy import create_engine, text, select, Table, Column, Integer, String, MetaData
import pandas as pd

# Create Conection

In [93]:
#conex√£o com bd
engine = create_engine("mssql+pyodbc://fdebierne:ggyQHJODSFH%%!GJJKS@metrix-wh.database.windows.net:1433/XXXFREMF_BACKUP?driver=ODBC+Driver+17+for+SQL+Server", echo = True)
conection = engine.connect()

2023-08-25 08:56:55,135 INFO sqlalchemy.engine.Engine SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
2023-08-25 08:56:55,149 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-08-25 08:56:55,368 INFO sqlalchemy.engine.Engine SELECT schema_name()
2023-08-25 08:56:55,371 INFO sqlalchemy.engine.Engine [generated in 0.00393s] ()
2023-08-25 08:56:55,833 INFO sqlalchemy.engine.Engine SELECT CAST('test max support' AS NVARCHAR(max))
2023-08-25 08:56:55,837 INFO sqlalchemy.engine.Engine [generated in 0.00361s] ()

## Example how to get a table

In [181]:
sql = """ SELECT *
    FROM MACRO_MEAN_SDV M
    WHERE M.STATEMENTYEAR = '2021'
    """
MACRO_MEAN_SDV_LPLIST_AVM_LPLIST_AVM_LPLIST_AVM_LPLIST_AVM_LPLIST_AVM_DF = pd.read_sql( sql, con=conection)

2023-08-23 16:18:51,192 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
FROM [INFORMATION_SCHEMA].[TABLES]
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
2023-08-23 16:18:51,192 INFO sqlalchemy.engine.Engine [generated in 0.00121s] ('BASE TABLE', " SELECT *\n    FROM MACRO_MEAN_SDV M\n    WHERE M.STATEMENTYEAR = '2021'\n    ", 'dbo')
2023-08-23 16:18:51,489 INFO sqlalchemy.engine.Engine  SELECT *
    FROM MACRO_MEAN_SDV M
    WHERE M.STATEMENTYEAR = '2021'

2023-08-23 16:18:51,489 INFO sqlalchemy.engine.Engine [raw sql] ()

In [182]:
MACRO_MEAN_SDV_DF

,MDRA_SUBTYPE_YR,NARRATIVE,MDRA_SUBTYPE,MDRA,SUBTYPE,STATEMENTYEAR,NumProperties_DATA,NumProperties_REV,NumProperties_FF,NumProperties_VAL,...,REV_2YR_PCT_CH_FWD_SDV,EXP_2YR_PCT_CH_FWD_SDV,NOI_2YR_PCT_CH_FWD_SDV,NCF_2YR_PCT_CH_FWD_SDV,CAPEX_2YR_PCT_CH_FWD_SDV,REV_3YR_PCT_CH_FWD_SDV,EXP_3YR_PCT_CH_FWD_SDV,NOI_3YR_PCT_CH_FWD_SDV,NCF_3YR_PCT_CH_FWD_SDV,CAPEX_3YR_PCT_CH_FWD_SDV
0,TN-Nashville-Davidson-Murfreesboro-Franklin_AL...,NaN,TN-Nashville-Davidson-Murfreesboro-Franklin_ALL,TN-Nashville-Davidson-Murfreesboro-Franklin,ALL,2021,174,169,134,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,NaN,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,TN-Nashville-Davidson-Murfreesboro-Franklin,GARDEN(ALL),2021,151,146,115,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,NaN,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,TN-Nashville-Davidson-Murfreesboro-Franklin,GARDEN(SB),2021,29,29,25,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,NaN,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,TN-Nashville-Davidson-Murfreesboro-Franklin,GARDEN,2021,122,117,90,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,NaN,TN-Nashville-Davidson-Murfreesboro-Franklin_GA...,TN-Nashville-Davidson-Murfreesboro-Franklin,GARDEN_MIDRISE(SB),2021,29,29,25,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,TN-AR-MS-Memphis_GARDEN_MIDRISE_HIRISE_2021,NaN,TN-AR-MS-Memphis_GARDEN_MIDRISE_HIRISE,TN-AR-MS-Memphis,GARDEN_MIDRISE_HIRISE,2021,51,50,39,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
831,TN-GA-Chattanooga_ALL_2021,NaN,TN-GA-Chattanooga_ALL,TN-GA-Chattanooga,ALL,2021,39,36,29,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
832,TN-GA-Chattanooga_GARDEN(ALL)_2021,NaN,TN-GA-Chattanooga_GARDEN(ALL),TN-GA-Chattanooga,GARDEN(ALL),2021,32,29,24,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
833,TN-Knoxville_ALL_2021,NaN,TN-Knoxville_ALL,TN-Knoxville,ALL,2021,53,50,38,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
834,TN-Knoxville_GARDEN(ALL)_2021,NaN,TN-Knoxville_GARDEN(ALL),TN-Knoxville,GARDEN(ALL),2021,43,40,29,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Imputs Procedure

In [94]:
# Filter
MDRA = 'Southeast' # Define the region of interest base on NCREIF
UWDATE_START = pd.Timestamp('2021-07-29')
UWDATE_END  = pd.Timestamp('2021-10-29')
SUBTYPE = 'ALL'
STATEMENTYEAR2 = 2021
MIN_NUMPROPS_FOR_US_MEAN_CALC = 1
DEPVAR='UW_CAPRATE'
MIN_NUMPROPS_IN_ST_MDRA_YR_TO_FIT_MODEL = 20
MODELNUM=0

# CHECK IF THERE ARE 1) ENOUGH OBSERVATIONS AND 2) US MEAN IS CALCULATED

## Imput Tables

### Get MACRO_MEAN_SDV Date

In [95]:
sql = """ SELECT *
    FROM MACRO_MEAN_SDV M
    WHERE M.STATEMENTYEAR = '2021'
    """
MACRO_MEAN_SDV_DF= pd.read_sql( sql, con=engine.connect())
MACRO_MEAN_SDV_DF.to_excel("source/MACRO_MEAN_SDV_DF.xlsx", index=False)
MACRO_MEAN_SDV_DF = pd.read_excel('source/MACRO_MEAN_SDV_DF.xlsx')

#Table MACRO_MEAN_SDV_DF

2023-08-25 08:57:18,301 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
FROM [INFORMATION_SCHEMA].[TABLES]
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
2023-08-25 08:57:18,303 INFO sqlalchemy.engine.Engine [generated in 0.00203s] ('BASE TABLE', " SELECT *\n    FROM MACRO_MEAN_SDV M\n    WHERE M.STATEMENTYEAR = '2021'\n    ", 'dbo')
2023-08-25 08:57:18,752 INFO sqlalchemy.engine.Engine  SELECT *
    FROM MACRO_MEAN_SDV M
    WHERE M.STATEMENTYEAR = '2021'

2023-08-25 08:57:18,753 INFO sqlalchemy.engine.Engine [raw sql] ()

### Get LPLIST_AVM

In [96]:
sql = """ SELECT *
    FROM LPLIST_AVM
    WHERE CENSUSYEAR = '2021'
    """
LPLIST_AVM_DF = pd.read_sql( sql, con=engine.connect())
LPLIST_AVM_DF.to_excel("source/LPLIST_AVM_DF.xlsx", index=False)
LPLIST_AVM_DF = pd.read_excel('source/LPLIST_AVM_DF.xlsx')

#table LPLIST_AVM_DF

2023-08-25 08:57:30,018 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
FROM [INFORMATION_SCHEMA].[TABLES]
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
2023-08-25 08:57:30,019 INFO sqlalchemy.engine.Engine [cached since 11.72s ago] ('BASE TABLE', " SELECT *\n    FROM LPLIST_AVM\n    WHERE CENSUSYEAR = '2021'\n    ", 'dbo')
2023-08-25 08:57:30,429 INFO sqlalchemy.engine.Engine  SELECT *
    FROM LPLIST_AVM
    WHERE CENSUSYEAR = '2021'

2023-08-25 08:57:30,430 INFO sqlalchemy.engine.Engine [raw sql] ()

## ALL US NUMBERS

In [131]:
#NumProperties_UW is used to verify something
NumProperties_UW_Filter = MACRO_MEAN_SDV_DF[(MACRO_MEAN_SDV_DF["SUBTYPE"] == 'ALL') & (MACRO_MEAN_SDV_DF["MDRA"] == 'ALLUS') & (MACRO_MEAN_SDV_DF["STATEMENTYEAR"] == STATEMENTYEAR2)] 

NumProperties_UW = NumProperties_UW_Filter["NumProperties_UW"].max()
NumProperties_UW

3969

## SUBTYPE_MDRA SDV

In [99]:
filtered_data = LPLIST_AVM_DF[
    (LPLIST_AVM_DF['UWDATE'] >= UWDATE_START) & (LPLIST_AVM_DF['UWDATE'] <= UWDATE_END) &
    (
        (LPLIST_AVM_DF['NCREIFMetro'] == MDRA) |
        (LPLIST_AVM_DF['NCREIFDivision'] == MDRA) |
        (LPLIST_AVM_DF['NCREIFRegion'] == MDRA) |
        (MDRA == 'ALLUS')
    ) &
    (
        (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == SUBTYPE) |
        (SUBTYPE == 'ALL') |
        (
            ((LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN') | (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE')) &
            (SUBTYPE == 'GARDEN_MIDRISE')
        ) |
        (
            ((LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE') | (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'HIRISE')) &
            (SUBTYPE == 'MIDRISE_HIRISE')
        ) |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'HIRISE')
            ) & (SUBTYPE == 'GARDEN_MIDRISE_HIRISE')
        ) |
        (
            ((LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN(SB)') | (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN')) &
            (SUBTYPE == 'GARDEN(ALL)')
        ) |
        (
            ((LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE(SB)') | (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE')) &
            (SUBTYPE == 'MIDRISE(ALL)')
        ) |
        (
            ((LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN(SB)') | (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE(SB)')) &
            (SUBTYPE == 'GARDEN_MIDRISE(SB)')
        )
    ) & (LPLIST_AVM_DF['DATANUM'].isin([0, 1, 2, 3]))
    ]

if DEPVAR == 'UW_CAPRATE':
    filtered_data = filtered_data[filtered_data['UW_CAPRATE'].notnull()]
elif DEPVAR == 'UW_REV_ACTUAL_RATIO':
    filtered_data = filtered_data[filtered_data['UW_REV_ACTUAL_RATIO'].notnull()]
elif DEPVAR == 'UW_EXP_ACTUAL_RATIO':
    filtered_data = filtered_data[filtered_data['UW_EXP_ACTUAL_RATIO'].notnull()]


#Temos uma diferen√ßa de 1 linha, provavelmente por causa de case insensitive

## PERFORM THE CALC

In [100]:
if NumProperties_UW > MIN_NUMPROPS_FOR_US_MEAN_CALC and len(filtered_data) >= MIN_NUMPROPS_IN_ST_MDRA_YR_TO_FIT_MODEL:
    STATEMENTYEAR1 = STATEMENTYEAR2
    def define_variables(variable_name):
        #primeiro pegamos o nome da variavel e separamos por split
        variables_name_split = variable_name.split('_')

        for v in variables_name_split:
            if(v == 'MDRA'):
                variable = MDRA
            elif(v == 'SUBTYPE'):
                variable = variable + '_' + str(SUBTYPE)
            elif(v == 'YR1'):
                variable = variable + '_' + str(STATEMENTYEAR1)
            elif(v == 'YR2'):
                variable = variable + '_' + str(STATEMENTYEAR2)
            elif(v == 'VAR'):
                variable = variable + '_' + str(DEPVAR)
            elif(v == 'NUM'):
                variable = variable + '_' + str(MODELNUM)
        
        return variable 
        
    variables = {"MDRA_SUBTYPE_YR1_YR2_VAR_NUM": define_variables('MDRA_SUBTYPE_YR1_YR2_VAR_NUM'), "MDRA_SUBTYPE_YR1_YR2": define_variables('MDRA_SUBTYPE_YR1_YR2'), "MDRA_SUBTYPE_YR2_VAR": define_variables('MDRA_SUBTYPE_YR2_VAR'), "MDRA_SUBTYPE_VAR": define_variables('MDRA_SUBTYPE_VAR'), "MDRA_SUBTYPE_YR2":define_variables('MDRA_SUBTYPE_YR2')}

## SUBTYPE_MDRA SDV

### TEMP TUS

In [120]:
conditions_TUS = (
    (MACRO_MEAN_SDV_DF['SUBTYPE'] == SUBTYPE) &
    (MACRO_MEAN_SDV_DF['MDRA'] == MDRA) &
    (MACRO_MEAN_SDV_DF['STATEMENTYEAR'] >= STATEMENTYEAR1) &
    (MACRO_MEAN_SDV_DF['STATEMENTYEAR'] <= STATEMENTYEAR2) &
    (MACRO_MEAN_SDV_DF['NumProperties_UW'] > MIN_NUMPROPS_FOR_US_MEAN_CALC)
)

In [134]:
#NUMPROPYEAR column calculation
NUMPROPYEAR_DF = LPLIST_AVM_DF[
    (LPLIST_AVM_DF['UWDATE'] >= UWDATE_START) &
    (LPLIST_AVM_DF['UWDATE'] <= UWDATE_END) &
    (
        (LPLIST_AVM_DF['NCREIFMetro'] == MDRA) |
        (LPLIST_AVM_DF['NCREIFDivision'] == MDRA) |
        (LPLIST_AVM_DF['NCREIFRegion'] == MDRA) |
        (MDRA == 'ALLUS')
    
    ) &
    (
        (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == SUBTYPE) |
        (SUBTYPE == 'ALL') |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE')
            ) 
            & (SUBTYPE == 'GARDEN_MIDRISE')
        ) |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'HIRISE')
            )
            & (SUBTYPE == 'MIDRISE_HIRISE')
        ) |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'HIRISE')
            )  
            & (SUBTYPE == 'GARDEN_MIDRISE_HIRISE')
        ) |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN(SB)') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN')
            ) & (SUBTYPE == 'GARDEN(ALL)')
        ) |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE(SB)') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE')
            ) & (SUBTYPE == 'MIDRISE(ALL)')
        ) |
        (
            (
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'GARDEN(SB)') |
                (LPLIST_AVM_DF['PROPERTYSUBTYPE_ASSIGNED'] == 'MIDRISE(SB)')
            ) & (SUBTYPE == 'GARDEN_MIDRISE(SB)')
        )
    ) &
    (LPLIST_AVM_DF['DATANUM'].isin([0, 1, 2, 3])) &
    (
        (
            (DEPVAR == 'UW_CAPRATE') & (LPLIST_AVM_DF[DEPVAR].notnull())
        ) |
        (
            (DEPVAR == 'UW_REV_ACTUAL_RATIO') & (LPLIST_AVM_DF[DEPVAR].notnull())
        ) |
        (
            (DEPVAR == 'UW_EXP_ACTUAL_RATIO') & (LPLIST_AVM_DF[DEPVAR].notnull())
        )
    ) 
    ]
NUMPROPYEAR = len(NUMPROPYEAR_DF)
NUMPROPYEAR

164

In [133]:
#v column calculation
V_TUS_DF = MACRO_MEAN_SDV_DF[
        (
            (
                (DEPVAR == 'UW_CAPRATE') & (MACRO_MEAN_SDV_DF[DEPVAR].notnull())
            ) |
            (
                (DEPVAR == 'UW_REV_ACTUAL_RATIO') & (MACRO_MEAN_SDV_DF[DEPVAR].notnull())
            ) |
            (
                (DEPVAR == 'UW_EXP_ACTUAL_RATIO') & (MACRO_MEAN_SDV_DF[DEPVAR].notnull())
            )
        ) 
    ]

V_TUS = V_TUS_DF[DEPVAR]
V_TUS

0      0.045706
1      0.045351
2      0.044415
3      0.045551
4      0.044415
         ...
830    0.055203
831    0.053530
832    0.053530
833    0.051157
834    0.051157
Name: UW_CAPRATE, Length: 820, dtype: float64

In [123]:
tus = {
    'STATEMENTYEAR': MACRO_MEAN_SDV_DF['STATEMENTYEAR'],
    'NUMPROPYEAR': NUMPROPYEAR,
    'V': V_TUS,
    'YearBuiltRenov': MACRO_MEAN_SDV_DF['YearBuiltRenov'],
    'PopulationPerSqMile': MACRO_MEAN_SDV_DF['PopulationPerSqMile'],
    'MedianHHInc': MACRO_MEAN_SDV_DF['MedianHHInc'],
    'MedianHomeVal': MACRO_MEAN_SDV_DF['MedianHomeVal'],
    'Median_Rent': MACRO_MEAN_SDV_DF['Median_Rent'],
    'MedianAge': MACRO_MEAN_SDV_DF['MedianAge'],
    'Median_Owner_Costs': MACRO_MEAN_SDV_DF['Median_Owner_Costs'],
    'RenterPCT': MACRO_MEAN_SDV_DF['RenterPCT'],
    'CashRentOver30PCT': MACRO_MEAN_SDV_DF['CashRentOver30PCT'],
    'BachelorsOrMorePCT': MACRO_MEAN_SDV_DF['BachelorsOrMorePCT'],
    'UnemploymentPCT': MACRO_MEAN_SDV_DF['UnemploymentPCT'],
    'MngtFinancePCT': MACRO_MEAN_SDV_DF['MngtFinancePCT'],
    'MovedIn2010orLaterPCT': MACRO_MEAN_SDV_DF['MovedIn2010orLaterPCT'],
    'HPI_1YRCH': MACRO_MEAN_SDV_DF['HPI_1YRCH'],
    'NumUnits': MACRO_MEAN_SDV_DF['NumUnits'],
    'HPI_METRO_1YRCH': MACRO_MEAN_SDV_DF['HPI_METRO_1YRCH']
}

TUS_DF_ORIGIN = pd.DataFrame(tus)

columns_to_select = ['STATEMENTYEAR', 'NUMPROPYEAR', 'V', 'YearBuiltRenov', 'PopulationPerSqMile',
                     'MedianHHInc', 'MedianHomeVal', 'Median_Rent', 'MedianAge', 'Median_Owner_Costs',
                     'RenterPCT', 'CashRentOver30PCT', 'BachelorsOrMorePCT', 'UnemploymentPCT', 'MngtFinancePCT',
                     'MovedIn2010orLaterPCT', 'HPI_1YRCH', 'NumUnits', 'HPI_METRO_1YRCH']

TUS_DF = TUS_DF_ORIGIN.loc[conditions_TUS, columns_to_select]
TUS_DF = TUS_DF.drop_duplicates()
TUS_DF

,STATEMENTYEAR,NUMPROPYEAR,V,YearBuiltRenov,PopulationPerSqMile,MedianHHInc,MedianHomeVal,Median_Rent,MedianAge,Median_Owner_Costs,RenterPCT,CashRentOver30PCT,BachelorsOrMorePCT,UnemploymentPCT,MngtFinancePCT,MovedIn2010orLaterPCT,HPI_1YRCH,NumUnits,HPI_METRO_1YRCH
793,2021,164,0.05005,2002.549805,4949.651855,55839.34375,216611.110677,1203.239258,37.072852,1433.625326,0.557452,0.512142,0.327347,0.059385,0.220193,0.713541,0.138293,193.460612,0.138293

### TEMP T0

In [139]:
#v column calculation
V_T0_DF = LPLIST_AVM_DF[
        (
            (
                (DEPVAR == 'UW_CAPRATE') & (LPLIST_AVM_DF[DEPVAR].notnull())
            ) |
            (
                (DEPVAR == 'UW_REV_ACTUAL_RATIO') & (LPLIST_AVM_DF[DEPVAR].notnull())
            ) |
            (
                (DEPVAR == 'UW_EXP_ACTUAL_RATIO') & (LPLIST_AVM_DF[DEPVAR].notnull())
            )
        ) 
    ]

V_T0 = V_T0_DF[DEPVAR]
V_T0

0       0.055768
1       0.064044
2       0.073334
3       0.074945
4       0.058246
          ...
8003    0.038864
8004    0.034401
8005    0.038595
8006    0.042566
8007    0.045998
Name: UW_CAPRATE, Length: 7325, dtype: float64

In [88]:
conditions = (
    (LPLIST_AVM_DF['UWDATE'] >= UWDATE_START) &
    (LPLIST_AVM_DF['UWDATE'] <= UWDATE_END) &
    (TUS_DF['STATEMENTYEAR'] >= STATEMENTYEAR1) &
    (TUS_DF['STATEMENTYEAR'] == STATEMENTYEAR2) &
    ((LPLIST_AVM_DF['NCREIFMetro'] == MDRA) | (LPLIST_AVM_DF['NCREIFDivision'] == MDRA) | (LPLIST_AVM_DF['NCREIFRegion'] == MDRA) | (MDRA == 'Southeast')) &
    (LPLIST_AVM_DF['YearBuiltRenov'].notnull()) &
    (LPLIST_AVM_DF['PopulationPerSqMile'].notnull()) &
    (LPLIST_AVM_DF['MedianHHInc'].notnull()) &
    (LPLIST_AVM_DF['MedianHomeVal'].notnull()) &
    (LPLIST_AVM_DF['Median_Rent'].notnull()) &
    (LPLIST_AVM_DF['MedianAge'].notnull()) &
    (LPLIST_AVM_DF['Median_Owner_Costs'].notnull()) &
    (LPLIST_AVM_DF['RenterPCT'].notnull()) &
    (LPLIST_AVM_DF['CashRentOver30PCT'].notnull()) &
    (LPLIST_AVM_DF['BachelorsOrMorePCT'].notnull()) &
    (LPLIST_AVM_DF['UnemploymentPCT'].notnull()) &
    (LPLIST_AVM_DF['MngtFinancePCT'].notnull()) &
    (LPLIST_AVM_DF['MovedIn2010orLaterPCT'].notnull()) &
    (LPLIST_AVM_DF['HPI_1YRCH'].notnull()) &
    (LPLIST_AVM_DF['NumUnits'].notnull()) &
    (   
        (
            (DEPVAR == 'UW_CAPRATE') & (LPLIST_AVM_DF['UW_CAPRATE'].notnull())
        ) |
        (
            (DEPVAR == 'UW_REV_ACTUAL_RATIO') & (LPLIST_AVM_DF['UW_REV_ACTUAL_RATIO'].notnull())
        ) |
        (
            (DEPVAR == 'UW_EXP_ACTUAL_RATIO') & (LPLIST_AVM_DF['UW_EXP_ACTUAL_RATIO'].notnull())
        )
    )
)

In [145]:
#create temp table tus
T = {
    'STATEMENTYEAR': TUS_DF['STATEMENTYEAR'],
    'V': V_T0,
    'V1': LPLIST_AVM_DF['YearBuiltRenov'] - TUS_DF['YearBuiltRenov'],
    'V2': LPLIST_AVM_DF['PopulationPerSqMile'] - TUS_DF['PopulationPerSqMile'],
    'V3': LPLIST_AVM_DF['MedianHHInc'] - TUS_DF['MedianHHInc'],
    'V4': LPLIST_AVM_DF['MedianHomeVal'] - TUS_DF['MedianHomeVal'],
    'V5': LPLIST_AVM_DF['Median_Rent'] - TUS_DF['Median_Rent'],
    'V6': LPLIST_AVM_DF['MedianAge'] - TUS_DF['MedianAge'],
    'V7': LPLIST_AVM_DF['Median_Owner_Costs'] - TUS_DF['Median_Owner_Costs'],
    'V8': LPLIST_AVM_DF['RenterPCT'] - TUS_DF['RenterPCT'],
    'V9': LPLIST_AVM_DF['CashRentOver30PCT'] - TUS_DF['CashRentOver30PCT'],
    'V10': LPLIST_AVM_DF['BachelorsOrMorePCT'] - TUS_DF['BachelorsOrMorePCT'],
    'V11': LPLIST_AVM_DF['UnemploymentPCT'] - TUS_DF['UnemploymentPCT'],
    'V13': LPLIST_AVM_DF['MngtFinancePCT'] - TUS_DF['MngtFinancePCT'],
    'V15': LPLIST_AVM_DF['MovedIn2010orLaterPCT'] - TUS_DF['MovedIn2010orLaterPCT'],
    'V16': LPLIST_AVM_DF['HPI_1YRCH'] - TUS_DF['HPI_1YRCH'],
    'V35': LPLIST_AVM_DF['NumUnits'] - TUS_DF['NumUnits'],
    'V39': LPLIST_AVM_DF['HPI_METRO_1YRCH'] - TUS_DF['HPI_METRO_1YRCH']
}

T_DF_ORIGIN = pd.DataFrame(T)

columns_to_select = ['STATEMENTYEAR','V','V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V13','V15','V16','V35','V39']

T_DF = T_DF_ORIGIN.loc[conditions, columns_to_select]
T_DF

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [85]:
TUS_DF['STATEMENTYEAR']

793    2021
Name: STATEMENTYEAR, dtype: int64